name: Build OpenWrt TL-MR3020 v1

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up OpenWrt build environment
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Configure OpenWrt
        run: |
          make menuconfig
        env:
          CONFIG_TARGET: ath79
          CONFIG_TARGET_SUBTARGET: tiny
          CONFIG_TARGET_PROFILE: tl-mr3020-v1
          CONFIG_PACKAGE_luci: n
          CONFIG_PACKAGE_p910nd: y

      - name: Build firmware
        run: |
          make -j$(nproc) V=s

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: bin/targets/ath79/tiny/openwrt-*.bin
